# Copyright (c) 2021, ArrayFire
# All rights reserved.
#
# This file is distributed under 3-clause BSD license.
# The complete license agreement can be obtained at:
# http://arrayfire.com/licenses/BSD-3-Clause

FetchContent_Declare(
  ${clblas_prefix}
  GIT_REPOSITORY    https://github.com/arrayfire/clBLAS.git
  GIT_TAG           cmake_fixes
)
FetchContent_Populate(${clblas_prefix})

set(current_build_type ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS OFF)
add_subdirectory(${${clblas_prefix}_SOURCE_DIR}/src ${${clblas_prefix}_BINARY_DIR} EXCLUDE_FROM_ALL)
set(BUILD_SHARED_LIBS ${current_build_type})

mark_as_advanced(
  INSTALL_SRC
  AUTOGEMM_ARCHITECTURE
  Boost_PROGRAM_OPTIONS_LIBRARY_RELEASE
  CLBLAS_BUILD64
  CLBLAS_BUILD_CALLBACK_CLIENT
  CLBLAS_BUILD_CLIENT
  CLBLAS_BUILD_EXAMPLES
  CLBLAS_BUILD_LOADLIBRARIES
  CLBLAS_BUILD_RUNTIME
  CLBLAS_BUILD_TEST
  CLBLAS_CODE_COVERAGE
  CLBLAS_SUFFIX_BIN
  CLBLAS_SUFFIX_LIB
  BLAS_DEBUG_TOOLS
  BLAS_DUMP_CLBLAS_KERNELS
  BLAS_KEEP_KERNEL_SOURCES
  BLAS_PRINT_BUILD_ERRORS
  BLAS_TRACE_MALLOC
  CLBLAS_BUILD_KTEST
  CLBLAS_BUILD_PERFORMANCE
  CLBLAS_BUILD_SAMPLE
  CORR_TEST_WITH_ACML
  OPENCL_COMPILER_DIR
  OPENCL_VERSION
  PRECOMPILE_GEMM_PRECISION_CGEMM
  PRECOMPILE_GEMM_PRECISION_DGEMM
  PRECOMPILE_GEMM_PRECISION_SGEMM
  PRECOMPILE_GEMM_PRECISION_ZGEMM
  PRECOMPILE_GEMM_TRANS_CC
  PRECOMPILE_GEMM_TRANS_CN
  PRECOMPILE_GEMM_TRANS_CT
  PRECOMPILE_GEMM_TRANS_NC
  PRECOMPILE_GEMM_TRANS_NN
  PRECOMPILE_GEMM_TRANS_NT
  PRECOMPILE_GEMM_TRANS_TC
  PRECOMPILE_GEMM_TRANS_TN
  PRECOMPILE_GEMM_TRANS_TT
  PRECOMPILE_TRSM_DTRSM
  PRECOMPILE_TRSM_STRSM
  TARGET_PLATFORM
)
