if (ArrayFire_CPU_FOUND)
    if (TARGET afcpu)
        set(BUILD_CPU_EXAMPLES ${BUILD_CPU})
    else ()
        set(BUILD_CPU_EXAMPLES ON)
    endif ()
else ()
    set(BUILD_CPU_EXAMPLES OFF)
endif ()

if (ArrayFire_CUDA_FOUND)
    if (TARGET afcpu)
        set(BUILD_CUDA_EXAMPLES ${BUILD_CUDA})
    else ()
        set(BUILD_CUDA_EXAMPLES ON)
    endif ()
else ()
    set(BUILD_CUDA_EXAMPLES OFF)
endif ()

if (ArrayFire_OpenCL_FOUND)
    if (TARGET afcpu)
        set(BUILD_OPENCL_EXAMPLES ${BUILD_OPENCL})
    else ()
        set(BUILD_OPENCL_EXAMPLES ON)
    endif ()
else ()
    set(BUILD_OPENCL_EXAMPLES OFF)
endif ()

if (ArrayFire_Unified_FOUND)
    if (TARGET af)
        set(BUILD_UNIFIED_EXAMPLES ${BUILD_UNIFIED})
    else ()
        set(BUILD_UNIFIED_EXAMPLES ON)
    endif ()
else ()
    set(BUILD_UNIFIED_EXAMPLES OFF)
endif ()
