on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: ci

jobs:
  clang-format:
      name: Clang Format Lint
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Respository
            uses: actions/checkout@master

          - name: Check Sources
            uses: DoozyX/clang-format-lint-action@v0.11
            with:
              source: './src'
              extensions: 'h,cpp,hpp'
              clangFormatVersion: 11

          - name: Check Tests
            uses: DoozyX/clang-format-lint-action@v0.11
            with:
              source: './test'
              extensions: 'h,cpp,hpp'
              clangFormatVersion: 11

          - name: Check Examples
            uses: DoozyX/clang-format-lint-action@v0.11
            with:
              source: './examples'
              extensions: 'h,cpp,hpp'
              clangFormatVersion: 11
